-- create
CREATE TABLE EMPLOYEE (
  Id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
  address TEXT NOT NULL
);

-- insert
INSERT INTO EMPLOYEE VALUES (0001, 'Clark', 18, 'Москва');
INSERT INTO EMPLOYEE VALUES (0002, 'Dave', 35,'Гродно');
INSERT INTO EMPLOYEE VALUES (0003, 'Ava', 25,'Минск');
INSERT INTO EMPLOYEE VALUES (0004, 'Eva', 32,'Питер');
INSERT INTO EMPLOYEE VALUES (0005, 'Ivan', 28,'Париж');
INSERT INTO EMPLOYEE VALUES (0006, 'Kate', 27,'Минск');
INSERT INTO EMPLOYEE VALUES (0007, 'Maks', 42,'Питер');
INSERT INTO EMPLOYEE VALUES (0008, 'Petr', 28,'Париж');

-- fetch 
SELECT * FROM EMPLOYEE WHERE address = 'Минск';